baseURL = "http://peopledoingfitness.com/"
languageCode = "en-us"
title = "People Doing Fitness"

theme = "jeffprod"
disqusShortname = "people-doing-fitness"

[permalinks]
    blog = "/:year/:month/:day/:filename"
    wod = "/wod/:year/:month/:day"

[taxonomies]
    tag = "tags"
    archive = "archives"



