version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
        # @ checked with sha256:ed3cc8bbd2a1c99a3e9f3409dba8f56aba98a9f3b40b0c89dbb8f43a993984dd

    steps:
      - checkout

      - run:
          name: Download Hugo
          command:
            curl -s https://api.github.com/repos/gohugoio/hugo/releases/22542425  | grep  browser_download_url  | grep Linux-64bit.deb  | grep -v extended  | cut -d '"' -f 4  | wget -i -

      - run:
          name: Install Hugo
          command:
            sudo dpkg -i hugo*_Linux-64bit.deb

      - run:
          name: Display version
          command:
            hugo version

      - run:
          name: Set PK permissions
          command: sudo chmod 400 ashevchenko.pem

      - run:
           name: build
           command: hugo

      - run:
          name: Clean copy dir
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "rm -rf pdf-build"

      - run:
          name: Copy over build
          command: scp -i ashevchenko.pem -o "StrictHostKeyChecking=no" -r public ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com:pdf-build

      - run:
          name: Deploy build
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "./pdf-update.sh"