version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-curl-browsers
    #machine:
      #image: ubuntu-1604:201903-01

    steps:
      - checkout

#      - run:
#          name: Install Snap
#          command:
#            sudo apt install snapd
## snap version
#
#      - run:
#          name: Snap version
#          command:
#            snap version
#
#      - run:
#          name: Snap status
#          command:
#            systemctl status snapd.service

#      - run:
#          name: Install Hugo
#          command:
#            sudo snap install hugo

      - run:
          name: Download hugo
          command:
            curl -s https://api.github.com/repos/gohugoio/hugo/releases/20845719  | grep  browser_download_url  | grep Linux-64bit.deb  | grep -v extended  | cut -d '"' -f 4  | wget -i -

#      #- run:
#      #   name: build
#      #   command: add snap to path?
#
      - run:
          name: install Hugo
          command:
            sudo dpkg -i hugo*_Linux-64bit.deb

      - run:
          name: Display version through snap
          command:
            hugo version

      - run:
          name: Set PK permissions
          command: sudo chmod 400 ashevchenko.pem

      - run:
           name: build
           command: hugo

      - run:
          name: Clean copy dir
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "rm -rf pdf-build"

      - run:
          name: Copy over build
          command: scp -i ashevchenko.pem -o "StrictHostKeyChecking=no" -r public ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com:pdf-build

      - run:
          name: Deploy build
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "./pdf-update.sh"