version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Update apt-get
          command:
            sudo apt-get -y -qq update

      - run:
          name: Install Hugo
          command:
            sudo apt-get -y install hugo

      #- run:
      #   name: build
      #   command: hugo

      - run:
           name: build
           command: touch test

      - run:
          name: Copy over build
          command: scp -i ashevchenko.pem -o "StrictHostKeyChecking=no" test ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com:pdf-build-test

      - run:
          name: Deploy build
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "./pdf-update.sh"