version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Install Hugo
          command:
            sudo snap install hugo

      #- run:
      #   name: build
      #   command: hugo

      #- run:
      #    name: Refresh Hugo
      #    command:
      #      sudo snap refresh hugo

      - run:
          name: Find Hugo
          command:
            snap find hugo

      - run:
          name: View Path
          command:
            echo $PATH

      - run:
          name: Add snap to path
          command:
            export PATH=/snap/bin:$PATH

      - run:
          name: View Path
          command:
            echo $PATH

      - run:
          name: Display version through snap
          command:
            snap run hugo version

      - run:
          name: Display version
          command:
            hugo version

      - run:
          name: Set PK permissions
          command: sudo chmod 400 ashevchenko.pem

      - run:
           name: build
           command: hugo

      - run:
          name: Copy over build
          command: scp -i ashevchenko.pem -o "StrictHostKeyChecking=no" -r public ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com:pdf-build

      - run:
          name: Deploy build
          command: ssh -i ashevchenko.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-3-123-146-68.eu-central-1.compute.amazonaws.com "./pdf-update.sh"